DROP DATABASE  IF EXISTS  `navidrone`;
CREATE DATABASE `navidrone`;

CREATE TABLE  `navidrone`.`UTILISATEUR` (
  `UTILISATEUR_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `UTILISATEUR_NOM` VARCHAR(20) NOT NULL,
  `UTILISATEUR_PRENOM` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`UTILISATEUR_ID`) USING BTREE,
  INDEX `IDX_UTILISATEUR_ID` (`UTILISATEUR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `navidrone`.`UTILISATEUR` (UTILISATEUR_NOM,UTILISATEUR_PRENOM) values ('TEST','BOB');
INSERT INTO `navidrone`.`UTILISATEUR` (UTILISATEUR_NOM,UTILISATEUR_PRENOM) values ('LEBON','LUANA');
select * from `navidrone`.`UTILISATEUR`;

DROP TABLE IF EXISTS `navidrone`.`COORD_GPS`;
CREATE TABLE  `navidrone`.`COORD_GPS` (
  `COORD_GPS_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `COORD_GPS_LATTITUDE` DECIMAL(11,8) NOT NULL,
  `COORD_GPS_LONGITUDE` DECIMAL(11,8) NOT NULL,
  PRIMARY KEY (`COORD_GPS_ID`) USING BTREE,
  INDEX `IDX_COORD_GPS_ID` (`COORD_GPS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585953, 1.461036);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585848, 1.461054);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585747, 1.461076);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585623, 1.461092);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585481, 1.461175);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585411, 1.461223);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585366, 1.461224);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585325, 1.461188);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585310, 1.461222);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585308, 1.461257);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585325, 1.461302);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585358, 1.461327);


CREATE TABLE  `navidrone`.`MISSION` (
  `MISSION_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `MISSION_NAME` VARCHAR(20),
  PRIMARY KEY (`MISSION_ID`) USING BTREE,
  INDEX `IDX_MISSION_ID` (`MISSION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `navidrone`.`MISSION` (MISSION_NAME) values ('MISSION_1');

CREATE TABLE  `navidrone`.`RELEVE` (
  `MISSION_ID` INT(10) NOT NULL,
  `COORD_GPS_ID` INT(10) NOT NULL,
  `PROFONDEUR` DECIMAL(11,8),  
  `DATE`       TIMESTAMP,
    PRIMARY KEY(`MISSION_ID`, `COORD_GPS_ID`),
    FOREIGN KEY (`MISSION_ID`) 
        REFERENCES `navidrone`.`MISSION`(`MISSION_ID`)
        ON DELETE CASCADE,	
    FOREIGN KEY (`COORD_GPS_ID`) 
        REFERENCES `navidrone`.`COORD_GPS`(`COORD_GPS_ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    

INSERT INTO `navidrone`.`RELEVE` (`MISSION_ID`, `COORD_GPS_ID`,`DATE`)
 SELECT `MISSION_ID`, `COORD_GPS_ID`, SYSDATE()
 FROM  `navidrone`.`MISSION`, `navidrone`.`COORD_GPS`;


CREATE TABLE  `navidrone`.`DRONE` (
  `DRONE_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `DRONE_NAME` VARCHAR(20),
  PRIMARY KEY (`DRONE_ID`) USING BTREE,
  INDEX `IDX_DRONE_ID` (`DRONE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `navidrone`.`DRONE` (DRONE_NAME) values ('DRONE_1');
INSERT INTO `navidrone`.`DRONE` (DRONE_NAME) values ('DRONE_2');

CREATE TABLE  `navidrone`.`FLOTTE` (
  `MISSION_ID` INT(10) NOT NULL,
  `DRONE_ID` INT(10) NOT NULL,
    PRIMARY KEY(`MISSION_ID`, `DRONE_ID`),
    FOREIGN KEY (`MISSION_ID`) 
        REFERENCES `navidrone`.`MISSION`(`MISSION_ID`)
        ON DELETE CASCADE,	
    FOREIGN KEY (`DRONE_ID`) 
        REFERENCES `navidrone`.`DRONE`(`DRONE_ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `navidrone`.`FLOTTE` (`MISSION_ID`, `DRONE_ID`)
 SELECT `MISSION_ID`, `DRONE_ID`
 FROM  `navidrone`.`MISSION`, `navidrone`.`DRONE`;
