DROP DATABASE  `navidrone`;
CREATE DATABASE `navidrone`;

CREATE TABLE  `navidrone`.`UTILISATEUR` (
  `UTILISATEUR_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `UTILISATEUR_NOM` VARCHAR(20) NOT NULL,
  `UTILISATEUR_PRENOM` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`UTILISATEUR_ID`) USING BTREE,
  INDEX `IDX_UTILISATEUR_ID` (`UTILISATEUR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `navidrone`.`UTILISATEUR` (UTILISATEUR_NOM,UTILISATEUR_PRENOM) values ('TEST','BOB');
select * from `navidrone`.`UTILISATEUR`;

DROP TABLE IF EXISTS `navidrone`.`COORD_GPS`;
CREATE TABLE  `navidrone`.`COORD_GPS` (
  `COORD_GPS_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `COORD_GPS_LATTITUDE` DECIMAL(11,8) NOT NULL,
  `COORD_GPS_LONGITUDE` DECIMAL(11,8) NOT NULL,
  PRIMARY KEY (`COORD_GPS_ID`) USING BTREE,
  INDEX `IDX_COORD_GPS_ID` (`COORD_GPS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585953, 1.461036);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585848, 1.461054);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585747, 1.461076);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585623, 1.461092);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585481, 1.461175);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585411, 1.461223);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585366, 1.461224);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585325, 1.461188);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585310, 1.461222);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585308, 1.461257);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585325, 1.461302);
INSERT INTO `navidrone`.`COORD_GPS` (COORD_GPS_LATTITUDE,COORD_GPS_LONGITUDE) values (43.585358, 1.461327);

select * from `navidrone`.`COORD_GPS`;

DROP TABLE IF EXISTS `navidrone`.`MISSION`;
CREATE TABLE  `navidrone`.`MISSION` (
  `MISSION_ID` INT(10) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`MISSION_ID`) USING BTREE,
  INDEX `IDX_MISSION_ID` (`MISSION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

select * from `navidrone`.`MISSION`;
